version: '3.8'

services:
  jenkins:
    image: imgjenkins
    container_name: 'jenkins'
    build: 
      context: jenkins_container/
    ports:
      - 8080:8080
    volumes:
      - $PWD/jenkinsbindmount:/var/jenkins_home
    networks:
      - network_jenkins

  ubuntu-server:
    image: imgubuntu
    container_name: 'ubuntu'
    build:
      context: ubuntu_container/
    networks:
      - network_jenkins

networks:
  network_jenkins:
    
    
    